FROM rust:1.47.0

RUN cargo install sccache

ENV HOME=/app
ENV SCCACHE_CACHE_SIZE="1G"
ENV SCCACHE_DIR=$HOME/.cache/sccache
ENV RUSTC_WRAPPER="/usr/local/cargo/bin/sccache"

WORKDIR $HOME

COPY . .

RUN --mount=type=cache,target=/app/.cache/sccache cargo build --release

ENTRYPOINT ["/app/target/release/app"]